apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: debot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: debot:latest
        imagePullPolicy: IfNotPresent  # Use local image from Docker Desktop
        command: ["streamlit", "run", "streamlit_app.py", "--server.address", "0.0.0.0"]
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef:
            name: debot-config
        - secretRef:
            name: debot-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: debot
spec:
  selector:
    app: chatbot
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer