apiVersion: v1
kind: ConfigMap
metadata:
  name: debot-config
  namespace: debot
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CHROMA_HOST: "chromadb-service"
  CHROMA_PORT: "8000"
  DEFAULT_LLM_PROVIDER: "groq"
  GROQ_MODEL: "llama3-8b-8192"
  DOCS_DIR: "/app/data/docs"
  PDF_DIR: "/app/data/pdfs"
  MDS_DIR: "/app/data/mds"