apiVersion: v1
kind: PersistentVolume
metadata:
  name: documents-pv
  namespace: debot
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/debot-documents
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents-pvc
  namespace: debot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi