apiVersion: v1
kind: Secret
metadata:
  name: debot-secrets
  namespace: debot
type: Opaque
data:
  # Base64 encoded values - update these with your actual keys
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # "postgres"
  GROQ_API_KEY: Z3NrX0Z1UlR0REJ3TUVLTnJsdnROUDVsV0dkeWIzRllMdWl6S3FlaE4xVFNyRkR3M0pSaHg2UjE=  # your_groq_key